-- Insert Companies data
INSERT INTO companies (id, registration_id, name, email, phone, address, company_type, status, registration_date, expiry_date, website, created_at, updated_at) VALUES
('cm001', 'INZ000303236', 'Bondbazaar Securities Private Limited', 'sheetal.musale@bondbazaar.com', '9821035471', '204-205 Balarama Co-Op Housing Society Ltd.,2Nd Floor Bandra Kurla Complex Bandra East Mumbai Maharashtra-400051', 'Securities', 'ACTIVE', NULL, NULL, 'https://www.bondbazaar.com', NOW(), NOW()),
('cm002', 'INZ000313632', 'Fourdegreewater Services Private Limited', 'compliance@wintwealth.com', '8861212984', '175, The Paviliondollars Colony, Near Rainbow Hospital Bannerghatta Main Road Bannerghatta Road Bangalore Karnataka - 5600076', 'Securities', 'ACTIVE', NULL, NULL, 'https://www.wintwealth.com/app/assets', NOW(), NOW()),
('cm003', 'INZ000310732', 'Goldenpi Securities Private Limited', 'ekta.sheth@goldenpi.com', '8017029917', '55/11 B And 55/B, 2Nd Sector Indiquibe Orion 24Th Main Hsr Layout Bangalore, Karnataka-560102', 'Securities', 'ACTIVE', NULL, NULL, 'https://www.goldenpi.com', NOW(), NOW()),
('cm004', 'INZ000312836', 'Grip Broking Private Limited', 'compliance@gripbroking.com', '9529095211', '106 Flat No. 106 Ii F New Asiatic Building H Block New Delhi East -110001', 'Securities', 'ACTIVE', NULL, NULL, 'https://www.gripinvest.in/', NOW(), NOW()),
('cm005', 'INZ000183631', 'ICICI Securities Limited', 'iseccompliance@icicisecurities.com', '9167997629', 'Icici Venture House Appa Saheb Marathe Marg Prabha Devi Mumbai Maharashtra-400025', 'Securities', 'ACTIVE', NULL, NULL, 'https://www.icicidirect.com', NOW(), NOW()),
('cm006', 'INZ000311637', 'India Bond Private Limited', 'compliance@indiabonds.com', '022-67544745', '605, 6Th Floor Windsor Off Cst Road Kalina Mumbai Maharashtra - 400098', 'Securities', 'ACTIVE', NULL, NULL, 'https://www.indiabonds.com/', NOW(), NOW()),
('cm007', 'INZ000315538', 'Jiraaf Platform Private Limited', 'richa.m@jiraaf.com', '9611312885', 'Clayworks, 1St Cross Road, 371 St. Johns Hospital Road Santoshpuram Koramangala 3Rd Block Bangalore Karnataka-560034', 'Securities', 'ACTIVE', NULL, NULL, 'https://www.jiraaf.com/', NOW(), NOW()),
('cm008', 'INZ000195834', 'JM Financial Services Limited', 'amar.agrawal@jmfl.com', '022-66303030', 'Cenergy,7 Floor Appa Saheb Marathe Marg Prabhadevi Mumbai,Maharashtra-400025', 'Securities', 'ACTIVE', NULL, NULL, 'https://www.jmfinancialservices.in', NOW(), NOW()),
('cm009', 'INZ000296636', 'Launchpad Fintech Private Limited', 'COMPLIANCE@BONDSINDIA.COM', '8595725516', '601/602, Express Building, 14 E Road, Churchgate, Mumbai - 400020', 'Securities', 'ACTIVE', NULL, NULL, 'https://www.bondsindia.com', NOW(), NOW()),
('cm010', 'INZ000158836', 'Motilal Oswal Financial Services Limited', 'Anupama.Bhattad@motilaloswal.com', '022-40548085', 'Motilal Oswal Tower Rahimtullah Say Ani Road Opposite Parel St Depot Prabhadevi Mumbai - Maharashtra-400025', 'Securities', 'ACTIVE', NULL, NULL, 'https://mofsl.co/OpenWeb/BrokerBranchDetails', NOW(), NOW()),
('cm011', 'INZ000314637', 'Stable Broking Private Limited', 'shubhangi.dubey@stablemoney.in', '7080414204', 'Block A, Stable Money, Bhive HSR Premium Campus,  Third Floor, Bommanahalli, Krishna Reddy Industrial Area,  Bangalore, Karnataka  - 560068', 'Securities', 'ACTIVE', NULL, NULL, 'https://bonds.stablemoney.in/', NOW(), NOW()),
('cm012', 'INZ000158031', 'Trust Securities Services Private Limited', 'richa.gandhi@trustgroup.in', '8082536452', '109/110, Balarama Bkc Bandra Mumbai Maharashtra-400051', 'Securities', 'ACTIVE', NULL, NULL, 'https://trustsecurities.in/', NOW(), NOW()),
('cm013', 'INZ000313336', 'Zephyr Financial Publishers  Private Limited', 'neelima@zephyr.org.in', '9920453866', '502 SN 12 Behind Kothrud Stand Chaitanyapuri Society Dahanukar Colony Kothrud Pune - 411308', 'Securities', 'ACTIVE', NULL, NULL, 'https://inrbonds.com/about-us', NOW(), NOW()),
('cm014', 'INZ000310534', 'Credavenue Securities Private Limited', 'vigneshwar.mohandhas@aspero.in', '9677104196', '12th Floor, Prestige Polygon, Annasalai, Nandanam, Chennai - 60035, Tamil Nadu', 'Securities', 'ACTIVE', NULL, NULL, 'https://www.aspero.in/', NOW(), NOW()),
('cm015', 'INZ000006031', 'Moneylicious Securities Private Limited', 'compliance@dhan.co', '9833689823', 'Unit No.2201, 22nd Floor, Gold Medal Avenue, S V Road, Beside Patel Petrol Pump, Piramal Nagar, Goregaon West Mumbai Maharashtra - 400104', 'Securities', 'ACTIVE', NULL, NULL, 'https://dhan.co/', NOW(), NOW()),
('cm016', 'INZ000318033', 'Fingeek Digital Private Limited', 'compliance@bondvue.com', '7003039921', '226/1, AJC Bose Road , Trinity, Unit No. 3B, Kolkata, Kolkata, West Bengal, India, 700020', 'Securities', 'ACTIVE', NULL, NULL, NULL, NOW(), NOW()),
('cm017', 'INZ000312534', 'Oro Financial Consultants Private Limited', 'compliance@incredmoney.com', '022-69041538', 'Unit No. 1203, 12th floor, B Wing, The Capital, Plot No. C - 70, G Block, BKC, Bandra East, Mumbai - 400 051', 'Securities', 'ACTIVE', NULL, NULL, 'https://www.biddeasy.com/', NOW(), NOW()),
('cm018', 'INZ000318831', 'Northern Arc Securities Private Limited', 'sornamukhi.j@northernarc.com', '8925922526', '10th floor, E block, IITM RESEARCH PARK, Kanagam Rd, Kanagam, Tharamani, Chennai, Tamil Nadu 600113', 'Securities', 'ACTIVE', NULL, NULL, 'https://altifi.ai/landing', NOW(), NOW()),
('cm019', 'INZ000025734', 'Sunrise Gilts & Securities Pvt Ltd', 'info@sunrisegilts.co.in', '9016962384', '514, 5Th Floor, Pinnacle Business Park, Opp Royal Orchid, Prahladnagar, Ahmedabad-380015, Gujarat', 'Securities', 'ACTIVE', NULL, NULL, 'https://www.sunrisegilts.com', NOW(), NOW()),
('cm020', 'INZ000213137', 'Nj India Invest Private Limited', 'varsha.saraf@njgroup.in', '9725048460', '901, 9Th Floor, Udhna Udyognagar Sangh Commercial Complex, Central Road No 10, Udhna, Surat-394210, Gujarat', 'Securities', 'ACTIVE', NULL, NULL, 'https://www.njwealth.in', NOW(), NOW()),
('cm021', 'INZ000320834', 'Sustvest Broking Private Limited', 'Vandana.j@sustvest.com', '8447218264', 'SCO NO. 32, 2ND FLOOR, M3M 113 M3M MARKET, SECTOR 113, NARSINGHPUR, GURGAON, HARYANA - 122004', 'Securities', 'ACTIVE', NULL, NULL, 'https://sustvest.com/', NOW(), NOW()),
('cm022', 'INZ000008037', 'Monarch Networth Capital Limited', 'cs@mnclgroup.com', '7208100881', 'Unit No. 803-804A, Unit No. PO4-01D, Tower A, 8th Floor, X-Change Plaza, Block No 53, WTC Gift City, Block No. 51, Road 5 E, Zone 5, Road -5E, Gift City, Gandhinagar, Gujarat – 382355', 'Securities', 'ACTIVE', NULL, NULL, 'https://www.mnclgroup.com/', NOW(), NOW()),
('cm023', 'INZ000169839', 'Eureka Stock & Share Broking Services Limited', 'debomita@eurekasec.com', '9836000908', '11th Floor, Merlin Infinite,1101,  DN-51 Salt Lake,  Sector 5, Bidhannagar, Kolkata - 700091', 'Securities', 'ACTIVE', NULL, NULL, 'https://www.eurekasec.com/', NOW(), NOW()),
('cm024', 'INZ000327831', 'Liquibonds India Pvt Ltd', 'secretarial@liquiloans.com', '7738640169', 'A-4005 Floor 40,plot 131/132, Indiabulls Blu A, Ganpatrao Kadam Marg, Worli, Delisle Road, Mumbai, Mumbai, Maharashtra, India, 400013', 'Securities', 'ACTIVE', NULL, NULL, 'https://www.liquibonds.in', NOW(), NOW());

-- Insert IPOs data
INSERT INTO ipos (id, name, symbol, issue_size, price_range, open_date, close_date, listing_date, status, exchange, created_at, updated_at) VALUES
('ipo001', 'Shringar House of Mangalsutra Ltd.', 'SHRINGAR', 0, NULL, NULL, NULL, NULL, 'BSE NSE', NULL, NOW(), NOW()),
('ipo002', 'Taurian MPS Ltd.', 'TAURIAN', 42.53, '162.00 to 171.00', NULL, NULL, NULL, 'UPCOMING', 'NSE SME', NOW(), NOW()),
('ipo003', 'Karbonsteel Engineering Ltd.', 'KARBON', 59.3, '151.00 to 159.00', NULL, NULL, NULL, 'UPCOMING', 'BSE SME', NOW(), NOW()),
('ipo004', 'Vashishtha Luxury Fashion Ltd.', 'VASHI', 8.87, '109.00 to 111.00', NULL, NULL, NULL, 'UPCOMING', 'BSE SME', NOW(), NOW()),
('ipo005', 'Sharvaya Metals Ltd.', 'SHARVAYA', 58.8, '192.00 to 196.00', NULL, NULL, NULL, 'UPCOMING', 'BSE SME', NOW(), NOW()),
('ipo006', 'Vigor Plast India Ltd.', 'VIGOR', 25.1, '77.00 to 81.00', NULL, NULL, NULL, 'UPCOMING', 'NSE SME', NOW(), NOW()),
('ipo007', 'Austere Systems Ltd.', 'AUSTERE', 15.57, '52.00 to 55.00', NULL, NULL, NULL, 'UPCOMING', 'BSE SME', NOW(), NOW()),
('ipo008', 'Optivalue Tek Consulting Ltd.', 'OPTI', 51.82, '80.00 to 84.00', NULL, NULL, NULL, 'UPCOMING', 'NSE SME', NOW(), NOW()),
('ipo009', 'Goel Construction Co.Ltd.', 'GOEL', 100.15, '250.00 to 263.00', NULL, NULL, NULL, 'UPCOMING', 'BSE SME', NOW(), NOW()),
('ipo010', 'Amanta Healthcare Ltd.', 'AMANTA', 126, '126', NULL, NULL, NULL, 'UPCOMING', 'BSE NSE', NOW(), NOW()),
('ipo011', 'Rachit Prints Ltd.', 'RACHIT', 19.49, '140.00 to 149.00', NULL, NULL, NULL, 'UPCOMING', 'BSE SME', NOW(), NOW()),
('ipo012', 'Sugs Lloyd Ltd.', 'SUGS', 85.66, '117.00 to 123.00', NULL, NULL, NULL, 'UPCOMING', 'BSE SME', NOW(), NOW()),
('ipo013', 'Snehaa Organics Ltd.', 'SNEHAA', 32.68, '122', NULL, NULL, NULL, 'UPCOMING', 'NSE SME', NOW(), NOW()),
('ipo014', 'Abril Paper Tech Ltd.', 'ABRIL', 13.42, '61', NULL, NULL, NULL, 'UPCOMING', 'BSE SME', NOW(), NOW()),
('ipo015', 'Oval Projects Engineering Ltd.', 'OVAL', 46.74, '80.00 to 85.00', NULL, NULL, NULL, 'OPEN', 'BSE SME', NOW(), NOW()),
('ipo016', 'Anlon Healthcare Ltd.', 'ANLON', 121.03, '91', NULL, NULL, NULL, 'CLOSED', 'BSE NSE', NOW(), NOW()),
('ipo017', 'Vikran Engineering Ltd.', 'VIKRAN', 772, '97', NULL, NULL, NULL, 'LISTED', 'BSE NSE', NOW(), NOW()),
('ipo018', 'Current Infraprojects Ltd.', 'CURRENT', 41.8, '80', NULL, NULL, NULL, 'LISTED', 'NSE SME', NOW(), NOW()),
('ipo019', 'Sattva Engineering Construction Ltd.', 'SATTVA', 35.38, '75', NULL, NULL, NULL, 'LISTED', 'NSE SME', NOW(), NOW()),
('ipo020', 'Globtier Infotech Ltd.', 'GLOBTIER', 31.05, '72', NULL, NULL, NULL, 'LISTED', 'BSE SME', NOW(), NOW()),
('ipo021', 'NIS Management Ltd.', 'NIS', 60.01, '111', NULL, NULL, NULL, 'LISTED', 'BSE SME', NOW(), NOW()),
('ipo022', 'Anondita Medicare Ltd.', 'ANONDITA', 69.5, '145', NULL, NULL, NULL, 'LISTED', 'NSE SME', NOW(), NOW()),
('ipo023', 'Shivashrit Foods Ltd.', 'SHIVA', 70.03, '142', NULL, NULL, NULL, 'LISTED', 'NSE SME', NOW(), NOW()),
('ipo024', 'Classic Electrodes (India) Ltd.', 'CLASSIC', 41.51, '87', NULL, NULL, NULL, 'LISTED', 'NSE SME', NOW(), NOW()),
('ipo025', 'ARC Insulation & Insulators Ltd.', 'ARC', 41.19, '125', NULL, NULL, NULL, 'LISTED', 'NSE SME', NOW(), NOW()),
('ipo026', 'Mangal Electrical Industries Ltd.', 'MANGAL', 400, '561', NULL, NULL, NULL, 'LISTED', 'BSE NSE', NOW(), NOW()),
('ipo027', 'Shreeji Shipping Global Ltd.', 'SHREEJI', 410.71, '252', NULL, NULL, NULL, 'LISTED', 'BSE NSE', NOW(), NOW()),
('ipo028', 'Gem Aromatics Ltd.', 'GEM', 451.25, '325', NULL, NULL, NULL, 'LISTED', 'BSE NSE', NOW(), NOW()),
('ipo029', 'LGT Business Connextions Ltd.', 'LGT', 28.09, '107', NULL, NULL, NULL, 'LISTED', 'BSE SME', NOW(), NOW()),
('ipo030', 'Vikram Solar Ltd.', 'VIKRAM', 2079.37, '332', NULL, NULL, NULL, 'LISTED', 'BSE NSE', NOW(), NOW()),
('ipo031', 'Patel Retail Ltd.', 'PATEL', 242.66, '255', NULL, NULL, NULL, 'LISTED', 'BSE NSE', NOW(), NOW()),
('ipo032', 'Studio LSD Ltd.', 'STUDIO', 74.25, '54', NULL, NULL, NULL, 'LISTED', 'NSE SME', NOW(), NOW()),
('ipo033', 'Regaal Resources Ltd.', 'REGAAL', 306, '102', NULL, NULL, NULL, 'LISTED', 'BSE NSE', NOW(), NOW()),
('ipo034', 'Mahendra Realtors & Infrastructure Ltd.', 'MAHENDRA', 49.45, '85', NULL, NULL, NULL, 'LISTED', 'NSE SME', NOW(), NOW()),
('ipo035', 'BlueStone Jewellery & Lifestyle Ltd.', 'BLUE', 1540.65, '517', NULL, NULL, NULL, 'LISTED', 'BSE NSE', NOW(), NOW()),
('ipo036', 'Icodex Publishing Solutions Ltd.', 'ICODEX', 42.03, '102', NULL, NULL, NULL, 'LISTED', 'BSE SME', NOW(), NOW()),
('ipo037', 'ANB Metal Cast Ltd.', 'ANB', 49.92, '156', NULL, NULL, NULL, 'LISTED', 'NSE SME', NOW(), NOW()),
('ipo038', 'Medistep Healthcare Ltd.', 'MEDISTEP', 16.1, '43', NULL, NULL, NULL, 'LISTED', 'NSE SME', NOW(), NOW()),
('ipo039', 'Star Imaging & Path Lab Ltd.', 'STAR', 69.47, '142', NULL, NULL, NULL, 'LISTED', 'BSE SME', NOW(), NOW()),
('ipo040', 'All Time Plastics Ltd.', 'ALLTIME', 400.6, '275', NULL, NULL, NULL, 'LISTED', 'BSE NSE', NOW(), NOW()),
('ipo041', 'Connplex Cinemas Ltd.', 'CONNPLEX', 90.27, '177', NULL, NULL, NULL, 'LISTED', 'NSE SME', NOW(), NOW()),
('ipo042', 'JSW Cement Ltd.', 'JSW', 3600.00, '147', NULL, NULL, NULL, 'LISTED', 'BSE NSE', NOW(), NOW()),
('ipo043', 'Sawaliya Foods Products Ltd.', 'SAWALIYA', 34.83, '120', NULL, NULL, NULL, 'LISTED', 'NSE SME', NOW(), NOW()),
('ipo044', 'Highway Infrastructure Ltd.', 'HIGHWAY', 130, '70', NULL, NULL, NULL, 'LISTED', 'BSE NSE', NOW(), NOW()),
('ipo045', 'Knowledge Realty Trust REIT', 'KNOWLEDGE', 4800.00, '100', NULL, NULL, NULL, 'LISTED', 'BSE NSE', NOW(), NOW()),
('ipo046', 'Bhadora Industries Ltd.', 'BHADORA', 55.62, '103', NULL, NULL, NULL, 'LISTED', 'NSE SME', NOW(), NOW()),
('ipo047', 'Parth Electricals & Engineering Ltd.', 'PARTH', 49.67, '170', NULL, NULL, NULL, 'LISTED', 'NSE SME', NOW(), NOW()),
('ipo048', 'Jyoti Global Plast Ltd.', 'JYOTI', 35.44, '66', NULL, NULL, NULL, 'LISTED', 'NSE SME', NOW(), NOW()),
('ipo049', 'Aaradhya Disposal Industries Ltd.', 'AARADHYA', 45.1, '116', NULL, NULL, NULL, 'LISTED', 'NSE SME', NOW(), NOW()),
('ipo050', 'BLT Logistics Ltd.', 'BLT', 9.72, '75', NULL, NULL, NULL, 'LISTED', 'BSE SME', NOW(), NOW()),
('ipo051', 'Essex Marine Ltd.', 'ESSEX', 23.01, '54', NULL, NULL, NULL, 'LISTED', 'BSE SME', NOW(), NOW()),
('ipo052', 'Flysbs Aviation Ltd.', 'FLYSBS', 102.53, '225', NULL, NULL, NULL, 'LISTED', 'NSE SME', NOW(), NOW()),
('ipo053', 'Cash Ur Drive Marketing Ltd.', 'CASH', 60.79, '130', NULL, NULL, NULL, 'LISTED', 'NSE SME', NOW(), NOW()),
('ipo054', 'Renol Polychem Ltd.', 'RENOL', 25.77, '105', NULL, NULL, NULL, 'LISTED', 'NSE SME', NOW(), NOW());

-- Insert Advisors data (complete dataset from CSV)
INSERT INTO advisors (id, registration_id, name, email, phone, address, status, registration_date, expiry_date, category, qualifications, specialization, created_at, updated_at) VALUES
('adv001', 'INA000017523', '1 Finance Private Limited', 'compliance@1finance.co.in', NULL, 'Unit No B- 1101/1102 11th Floor B Wing Lotus Corporate Park Off Western Express Highway Goregaon (E) MUMBAI MAHARASHTRA 400063', 'ACTIVE', NULL, NULL, 'Corporate', NULL, 'Investment Advisory', NOW(), NOW()),
('adv002', 'INA000017231', '21G INVESTMENT ADVISERS PRIVATE LIMITED', 'munjal2805@gmail.com', NULL, '2455 GR DN ARJAN NAGAR R S ROAD LUDHIANA PUNJAB 141003', 'ACTIVE', NULL, NULL, 'Corporate', NULL, 'Investment Advisory', NOW(), NOW()),
('adv003', 'INA200000365', '29K INVESTMENT ADVISERS PRIVATE LTD', NULL, NULL, 'No.390 7th Main 9th Cross Jayanagar 2nd Block BANGALORE KARNATAKA 560011', 'ACTIVE', NULL, NULL, 'Corporate', NULL, 'Investment Advisory', NOW(), NOW()),
('adv004', 'INA000000888', '360 ONE Investment Adviser and Trustee Services Limited', 'Rupam.nagvekar@iiflw.com', NULL, '7th Floor IIFL Centre Kamala Mills Compound Senapati Bapat Marg Lower Parel (West) MUMBAI MAHARASHTRA 400013', 'ACTIVE', NULL, NULL, 'Corporate', NULL, 'Investment Advisory', NOW(), NOW()),
('adv005', 'INA000020794', '3Q Financial Services LLP', 'ketan@3qwealth.com', NULL, '1195/2Anandi Gopal Apts F C Road Shivajinagar Pune PUNE MAHARASHTRA 411005', 'ACTIVE', NULL, NULL, 'Corporate', NULL, 'Wealth Management', NOW(), NOW()),
('adv006', 'INA200002536', '6 SIGMA WEALTH ADVISORS', '6sigmawealth@gmail.com', NULL, 'Suite 806 MLS Business Centre - Tower II - Floor 8 TVH Beliciaa Towers MRC Nagar CHENNAI TAMIL NADU 600028', 'ACTIVE', NULL, NULL, 'Individual', NULL, 'Wealth Advisory', NOW(), NOW()),
('adv007', 'INA200008291', '90-10 Financial Planners Pvt Ltd', 'rajesh@90to10.com', NULL, 'Jaiganesh New No.1 and Old No. 321 36th A Cross 7th Main 5th Block Jayanagar BANGALORE KARNATAKA 560041', 'ACTIVE', NULL, NULL, 'Corporate', NULL, 'Financial Planning', NOW(), NOW()),
('adv008', 'INA000016454', 'Aarti Mohan (Proprietor : Aurion Advisors)', 'AARTIM159@GMAIL.COM', NULL, 'Flat No. 5 Friendship Apartment 23rd Rd Bandra West MUMBAI MAHARASHTRA 400050', 'ACTIVE', NULL, NULL, 'Individual', NULL, 'Investment Advisory', NOW(), NOW()),
('adv009', 'INA100005050', 'AAUM INVESTMENT ADVISERS PRIVATE LIMITED', 'mahesh.parasuraman@gmail.com', NULL, 'Flat no. No. 6 Flat No. 006 Nanda Ashirwad Apartments No.1 Canara Bank Colony 2nd Main Chandra Layout Nagarbhavi Bengaluru North BANGALORE KARNATAKA 560072', 'ACTIVE', NULL, NULL, 'Corporate', NULL, 'Investment Advisory', NOW(), NOW()),
('adv010', 'INAIFSC10001', 'Aavishkaar Investment Advisers IFSC Private Limited', 'shyam@aavishkaar.in', NULL, '13B 6th Floor Techniplex II Off. Veer Savarkar Flyover Goregaon West MUMBAI MAHARASHTRA 400062', 'ACTIVE', NULL, NULL, 'Corporate', NULL, 'Investment Management', NOW(), NOW()),
('adv011', 'INA000015729', 'Abakkus Asset Manager Private Limited', 'shivam.pandey@abakkusinvest.com', NULL, '6th Floor Param House Shanti Nagar Santacruz Chembur Link Road Santacruz East MUMBAI MAHARASHTRA 400055', 'ACTIVE', NULL, NULL, 'Corporate', NULL, 'Asset Management', NOW(), NOW()),
('adv012', 'INA100015285', 'Abans Commodities India Private Limited', NULL, NULL, '36 37 38 Floor 3 Plot 227 NARIMAN BHAVAN VINAYAK KUMAR SHAH NCPA NARIMAN POINT MUMBAI MAHARASHTRA 400021', 'ACTIVE', NULL, NULL, 'Corporate', NULL, 'Commodities', NOW(), NOW()),
('adv013', 'INA000006703', 'Abhijit Talukdar', NULL, NULL, 'A602 Magnolia Enclave Nahar Amrit Shakti Chandivali MUMBAI MAHARASHTRA 400072', 'ACTIVE', NULL, NULL, 'Individual', NULL, 'Investment Advisory', NOW(), NOW()),
('adv014', 'INA000016029', 'Abhishake Mathur', NULL, NULL, '301 Wing B Hubtown Sunmist N S Phadke Road Andheri East MUMBAI MAHARASHTRA 400069', 'ACTIVE', NULL, NULL, 'Individual', NULL, 'Investment Advisory', NOW(), NOW()),
('adv015', 'INA000004047', 'ABHISHEK AGARWAL', NULL, NULL, '4th Floor Bundal Capital Kothrud Depot PUNE MAHARASHTRA 411038', 'ACTIVE', NULL, NULL, 'Individual', NULL, 'Investment Advisory', NOW(), NOW()),
('adv016', 'INA000018258', 'Abhishek Goel proprietor Primedin Investment Adviser', NULL, NULL, 'G-502 Parsvnath Prestige Sector 93A Noida NOIDA UTTAR PRADESH 201309', 'ACTIVE', NULL, NULL, 'Individual', NULL, 'Investment Advisory', NOW(), NOW()),
('adv017', 'INA100008045', 'ABHISHEK KUMAR', NULL, NULL, 'H-301 Umang Winter Hills Metro Pillar 768 Dwarka Mor Sewak Park DELHI NATIONAL CAPITAL TERRITORY OF DELHI 110059', 'ACTIVE', NULL, NULL, 'Individual', NULL, 'Investment Advisory', NOW(), NOW()),
('adv018', 'INA000019442', 'Abhishek Phore - Proprietor Control Wealth Advisers', NULL, NULL, '146-C 1st Floor Hastsal Uttam Nagar DELHI NATIONAL CAPITAL TERRITORY OF DELHI 110059', 'ACTIVE', NULL, NULL, 'Individual', NULL, 'Wealth Advisory', NOW(), NOW()),
('adv019', 'INA000019594', 'Abraham Cherian Proprietor 360 wealth advice', NULL, NULL, 'D705 Kumaradhara Block National Games Village Koramangala BANGALORE KARNATAKA 560047', 'ACTIVE', NULL, NULL, 'Individual', NULL, 'Wealth Advisory', NOW(), NOW()),
('adv020', 'INA200000910', 'ABUBAKR SIDDIQUE. A.G.', NULL, NULL, 'No.6 Ponni Amman Koil 2nd Street C. Pallavaram CHENNAI TAMIL NADU 600043', 'ACTIVE', NULL, NULL, 'Individual', NULL, 'Investment Advisory', NOW(), NOW()),
('adv021', 'INA000015774', 'Accelpru Investment Advisors', NULL, NULL, '95 Floor- 9 Plot- 223 Maker Chamber III Jamnalal Bajaj Marg Nariman Point MUMBAI MAHARASHTRA 400021', 'ACTIVE', NULL, NULL, 'Corporate', NULL, 'Investment Advisory', NOW(), NOW()),
('adv022', 'INA000017718', 'ACME INVESTMENT ADVISORS PRIVATE LIMITED', NULL, NULL, '622 Tower B 6th Floor World Trade Tower Sector 16 Noida NOIDA UTTAR PRADESH 201301', 'ACTIVE', NULL, NULL, 'Corporate', NULL, 'Investment Advisory', NOW(), NOW()),
('adv023', 'INA000003957', 'ACUITAS CAPITAL ADVISORS PRIVATE LIMITED', NULL, NULL, '101 Maker Chambers III Plot No. 223 Nariman Point MUMBAI MAHARASHTRA 400021', 'ACTIVE', NULL, NULL, 'Corporate', NULL, 'Capital Advisory', NOW(), NOW()),
('adv024', 'INA000005515', 'ADARSH AGRAWAL PROP. REGROW INVESTMENT', NULL, NULL, 'Apollo Square 232 Plot No. 7/2 Race Course Road INDORE MADHYA PRADESH 452001', 'ACTIVE', NULL, NULL, 'Individual', NULL, 'Investment Advisory', NOW(), NOW()),
('adv025', 'INA000019789', 'ADARSH NIMBORKAR', NULL, NULL, '49 PRASAD NAGAR JAITALA ROAD NAGPUR CITY MAHARASHTRA NAGPUR MAHARASHTRA 440022', 'ACTIVE', NULL, NULL, 'Individual', NULL, 'Investment Advisory', NOW(), NOW()),
('adv026', 'INA000013183', 'Adhish patel', NULL, NULL, '3 Royal Kadamb Bungalows Nr. Silver Square Complex Thaltej AHMEDABAD GUJARAT 380059', 'ACTIVE', NULL, NULL, 'Individual', NULL, 'Investment Advisory', NOW(), NOW()),
('adv027', 'INA200011736', 'Aditya Govindaraj', NULL, NULL, 'New 2 Old 75 2nd Street Karpagam Avenue R A Puram CHENNAI TAMIL NADU 600028', 'ACTIVE', NULL, NULL, 'Individual', NULL, 'Investment Advisory', NOW(), NOW()),
('adv028', 'INA000015312', 'ADV PARTNERS INVESTMENT ADVISER INDIA PRIVATE LIMITED', NULL, NULL, 'Unit No 1509 and 1510 15th Floor ONE BKC Plot No. C 66 G Block BKC Bandra East MUMBAI MAHARASHTRA 400051', 'ACTIVE', NULL, NULL, 'Corporate', NULL, 'Investment Advisory', NOW(), NOW()),
('adv029', 'INA000013262', 'Affirma Capital Investment Adviser India Private Limited', NULL, NULL, '9th Floor Avighna House 82 Dr.Annie Besant Road Worli Naka Worli MUMBAI MAHARASHTRA 400018', 'ACTIVE', NULL, NULL, 'Corporate', NULL, 'Investment Advisory', NOW(), NOW()),
('adv030', 'INZ000209921', '123 CAPITALS', NULL, NULL, NULL, 'ACTIVE', NULL, NULL, 'Broker', NULL, 'Securities Trading', NOW(), NOW()),
('adv031', 'INZ000246535', '4A SECURITIES LIMITED', NULL, NULL, NULL, 'ACTIVE', NULL, NULL, 'Broker', NULL, 'Securities Trading', NOW(), NOW()),
('adv032', 'INZ000010231', '5PAISA CAPITAL LIMITED', NULL, NULL, NULL, 'ACTIVE', NULL, NULL, 'Broker', NULL, 'Securities Trading', NOW(), NOW()),
('adv033', 'INZ000308458', '9 CAPITAL CONSULTANTS LLP', NULL, NULL, NULL, 'ACTIVE', NULL, NULL, 'Broker', NULL, 'Capital Advisory', NOW(), NOW()),
('adv034', 'INZ000216930', 'A C AGARWAL SHARE BROKERS PRIVATE LIMITED', NULL, NULL, NULL, 'ACTIVE', NULL, NULL, 'Broker', NULL, 'Share Broking', NOW(), NOW()),
('adv035', 'INZ000173014', 'A SWAMINATHAN', NULL, NULL, NULL, 'ACTIVE', NULL, NULL, 'Broker', NULL, 'Securities Trading', NOW(), NOW()),
('adv036', 'INZ000305026', 'A&G STOCK BROKING & CO', NULL, NULL, NULL, 'ACTIVE', NULL, NULL, 'Broker', NULL, 'Stock Broking', NOW(), NOW()),
('adv037', 'INZ000198136', 'A. C. CHOKSI SHARE BROKERS PVT. LTD.', NULL, NULL, NULL, 'ACTIVE', NULL, NULL, 'Broker', NULL, 'Share Broking', NOW(), NOW()),
('adv038', 'INZ000239939', 'A. K. EQUITIES PVT. LTD.', NULL, NULL, NULL, 'ACTIVE', NULL, NULL, 'Broker', NULL, 'Equity Trading', NOW(), NOW()),
('adv039', 'INZ000240830', 'A. K. STOCKMART PRIVATE LIMITED', NULL, NULL, NULL, 'ACTIVE', NULL, NULL, 'Broker', NULL, 'Stock Trading', NOW(), NOW()),
('adv040', 'INZ000292027', 'A. N. SECURITIES', NULL, NULL, NULL, 'ACTIVE', NULL, NULL, 'Broker', NULL, 'Securities Trading', NOW(), NOW()),
('adv041', 'INZ000212336', 'A.A.DOSHI SHARE & STOCK BROKERS LIMITED', NULL, NULL, NULL, 'ACTIVE', NULL, NULL, 'Broker', NULL, 'Share & Stock Broking', NOW(), NOW()),
('adv042', 'INZ000169733', 'A.G. SHARES & SECURITIES LTD.', NULL, NULL, NULL, 'ACTIVE', NULL, NULL, 'Broker', NULL, 'Share & Securities', NOW(), NOW()),
('adv043', 'INZ000194330', 'A.P.T. RESEARCH PRIVATE LIMITED', NULL, NULL, NULL, 'ACTIVE', NULL, NULL, 'Broker', NULL, 'Research & Trading', NOW(), NOW()),
('adv044', 'INZ000317632', 'AARITYA BROKING PRIVATE LIMITED', NULL, NULL, NULL, 'ACTIVE', NULL, NULL, 'Broker', NULL, 'Broking Services', NOW(), NOW()),
('adv045', 'INZ000291038', 'AARNIK SECURITIES PVT. LTD.', NULL, NULL, NULL, 'ACTIVE', NULL, NULL, 'Broker', NULL, 'Securities Trading', NOW(), NOW()),
('adv046', 'INZ000032733', 'ABANS BROKING SERVICES PVT LTD', NULL, NULL, NULL, 'ACTIVE', NULL, NULL, 'Broker', NULL, 'Broking Services', NOW(), NOW()),
('adv047', 'INZ000194431', 'ABANS SECURITIES PRIVATE LIMITED', NULL, NULL, NULL, 'ACTIVE', NULL, NULL, 'Broker', NULL, 'Securities Trading', NOW(), NOW()),
('adv048', 'INZ000310834', 'Abbott Wealth Management Limited', NULL, NULL, NULL, 'ACTIVE', NULL, NULL, 'Broker', NULL, 'Wealth Management', NOW(), NOW());
